server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # API
    location /api/ {
        proxy_pass http://api:8080;
        proxy_set_header Host $host;
    }

    # Статические файлы кинотеатра (постеры, видео, субтитры)
    location /cinema-storage/ {
        proxy_pass http://api:8080;
        proxy_set_header Host $host;
    }

    # Всё остальное – React
    location / {
        try_files $uri $uri/ /index.html;
    }
}